--liquibase formatted sql

--changeset rodichev:1
CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    created_at TIMESTAMP(6),
    email      VARCHAR(255) NOT NULL
        CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7
            UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255)
        CONSTRAINT users_role_check
            CHECK ((role)::TEXT = ANY ((ARRAY ['ADMIN'::CHARACTER VARYING, 'USER'::CHARACTER VARYING])::TEXT[])),
    updated_at TIMESTAMP(6),
    username   VARCHAR(255) NOT NULL
        CONSTRAINT ukr43af9ap4edm43mmtq01oddj6
            UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    category_name VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    product_amount      INTEGER
        CONSTRAINT products_product_amount_check
            CHECK (product_amount >= 0),
    product_article     VARCHAR(255) NOT NULL
        CONSTRAINT ukehpglvf9e3kakpgg63919xj57
            UNIQUE,
    created_at          TIMESTAMP(6),
    product_description VARCHAR(255),
    image_url           VARCHAR(255),
    name                VARCHAR(255) NOT NULL,
    product_price       NUMERIC(10, 2),
    updated_at          TIMESTAMP(6),
    category_id         BIGINT
        CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9
            REFERENCES categories
);

CREATE TABLE IF NOT EXISTS orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL REFERENCES users (id),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    address      TEXT           NOT NULL,
    order_status VARCHAR(255) DEFAULT 'PENDING'
        CHECK (order_status IN ('PENDING', 'CONFIRMED', 'PROCESSING',
                                'SHIPPED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY',
                                'DELIVERED')),
    order_date   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    created_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    product_article VARCHAR(100),
    product_name    VARCHAR(255)   NOT NULL,
    product_price   NUMERIC(10, 2) NOT NULL,
    quantity        INTEGER        NOT NULL,
    order_id        BIGINT
        CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w
            REFERENCES orders,
    product_id      BIGINT
        CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi
            REFERENCES products
);