CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    category_name VARCHAR(255)
);

ALTER TABLE categories
    OWNER TO postgres;

CREATE TABLE products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    product_amount      INTEGER
        CONSTRAINT products_product_amount_check
            CHECK (product_amount >= 0),
    product_article     VARCHAR(255) NOT NULL
        CONSTRAINT ukehpglvf9e3kakpgg63919xj57
            UNIQUE,
    created_at          TIMESTAMP(6),
    product_description VARCHAR(255),
    image               VARCHAR(255),
    name                VARCHAR(255) NOT NULL,
    product_price       NUMERIC(10, 2),
    updated_at          TIMESTAMP(6),
    category_id         BIGINT
        CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9
            REFERENCES categories
);

ALTER TABLE products
    OWNER TO postgres;

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    created_at TIMESTAMP(6),
    email      VARCHAR(255) NOT NULL
        CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7
            UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255)
        CONSTRAINT users_role_check
            CHECK ((role)::TEXT = ANY ((ARRAY ['ADMIN'::CHARACTER VARYING, 'USER'::CHARACTER VARYING])::TEXT[])),
    updated_at TIMESTAMP(6),
    username   VARCHAR(255) NOT NULL
        CONSTRAINT ukr43af9ap4edm43mmtq01oddj6
            UNIQUE
);

ALTER TABLE users
    OWNER TO postgres;

CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    address      VARCHAR(255),
    order_date   TIMESTAMP(6),
    order_status VARCHAR(255)
        CONSTRAINT orders_order_status_check
            CHECK ((order_status)::TEXT = ANY
                   ((ARRAY ['CREATED'::CHARACTER VARYING, 'CANCELLED'::CHARACTER VARYING, 'COMPLETED'::CHARACTER VARYING])::TEXT[])),
    total_amount NUMERIC(38, 2),
    user_id      BIGINT NOT NULL
        CONSTRAINT fk32ql8ubntj5uh44ph9659tiih
            REFERENCES users
);

ALTER TABLE orders
    OWNER TO postgres;

CREATE TABLE order_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    product_article VARCHAR(100),
    product_name    VARCHAR(255)   NOT NULL,
    product_price   NUMERIC(10, 2) NOT NULL,
    quantity        INTEGER        NOT NULL,
    order_id        BIGINT
        CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w
            REFERENCES orders,
    product_id      BIGINT
        CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi
            REFERENCES products
);

ALTER TABLE order_items
    OWNER TO postgres;

